### ISSUE TITLE
Package Control

### ISSUE THREAD

**Issue by dixhuit** [kyleshevlin/susy-snippets#1]
This looks great! Any plans to make it available via Package Control?

**Comment by kyleshevlin** [comment]
I had not considered that, but I think it's a good idea worth pursuing. Opening a milestone.

**Comment by kyleshevlin** [comment]
Just opened a pull request with Package Control to submit this.

**Comment by dixhuit** [comment]
Splendid. Fingers crossed...

**Comment by kyleshevlin** [comment]
Package was merged. You should now be able to get the snippets via Package Control.

**Comment by dixhuit** [comment]
Marvellous. Many thanks :)
